### Write someting to the screen
* `shift`+`enter`: execute cell (also the Run button)

## Navigation
### The notebook itself
* Untitled --> lecture_1
* `+` add a new cell below
* File-->Save and checkpoint -or- picture of floppy disk: save
* close browser window and type ctl+c twice on command line to exit
* Run: exectue a cell
* Menu: toggle between markdown and code cell
### Within the notebook
* modes: control (blue bar) and edit (green bar)

    - `esc` for control mode
    - `enter` or click for edit mode
* Control mode (blue bar)
    - `a`: new cell above
    - `b`: new cell below (also + button)
    - `d`+`d`: delete current cell
    - `m`: convert the cell to markdown (also menu)
    - `y`: convert cell to code
* Edit mode:
    - type code
    
### Markdown:
* bullets: symbols, indentation
* headings: `#`
* equations: "Latex" e.g. `$f(x) = x^{2}$` -->$f(x) = x^{2}$
* links
* pseudo html

## Python as a calculator

In [1]:
1+2

3

**Exercise 1**: Use python to calculate `3 + 5 * 4`

## Data Types part 1
* integer: whole number (no decimal)
* float: has a decimal (default in python 3)

## Operators in Python:
* `+, -`: addition and subtraction
* `*`: multiplication
* `/` floating point division
* `//`: integer division
* `%` : modulo
* `**`: exponent

**Exercise 2**: experiment with the different division operators dividing 5 by 3. How does the result vary betwen floating point and integer division?

In [2]:
5/3

1.6666666666666667

In [3]:
5//3

1

## Reusing input and output: variables
* use the `=` to assign any number to a variable
* saves time and typing
* prevents typos
* makes code easy to update
* can't start with a number (but can include numbers)
* case sensitive a is not equal to A

In [4]:
a = 5/3
a
b = 5
b
c = 3
c
b/c

1.6666666666666667

**Exercise 3:** Assign a value of 60.0 to a variable named `weight_kg`

In [5]:
weight_kg = 60.0
weight_kg

60.0

Note that the notebook only shows us the last line - what if we wanted to see each line?

# Functions

* definition: a block of code that takes does something
* formula: `output = function(input)` or just `function(input)` if you don't want to save the output
    - usually takes input
    - usually returns output
    - always need parentheses
* reusable
* saves time and typing
* prevents typos
* makes code easy to update
* cannot start with a number (but can include numbers)
* case sensitive (python convention is for functions to be all lower case)
* lots of prewritten functions e.g. `print`


In [6]:
print(weight_kg)

60.0


**Exercise 4:** set the print function above equal to a variable. What happens when you print the variable?

In [7]:
x = print(weight_kg)
print(x)

60.0
None


# Data Types Part 2:
Everything in python has a data type:
* `function`
* `string`: letters, surround in single or double quotes
* `None`
* `list`: collection of objects
etc

Use the `type` function to figure out what data type an object is

In [8]:
type(print)

builtin_function_or_method

**Exercise 5:** Use the `type` function to find the data types of the following (try guessing what they will be before you check):
* weight_kg
* 'oxygen'
* str
* 1
* 1.0
* [1,3,5]
* None

In [9]:
print(type(weight_kg))
print(type('oxygen'))
print(type(str))
print(type(1))
print(type(1.0))
print(type([1,3,5]))
print(type(None))

<class 'float'>
<class 'str'>
<class 'type'>
<class 'int'>
<class 'float'>
<class 'list'>
<class 'NoneType'>


# Functions with multiple input values
inputs are separated with a comma

In [10]:
round(3.14159, 3)

3.142

# Writing your own function:
* formula:   
`def function_name(input1, input2):`                  <-- can be any function_name, can have as many variables as you want, colon required   
`    thing you want to do, end with defining output`  <-- must be indented, convention 4 spaces (avoid tabs)  
`    return output`  <-- also must be indented
indentation is how python knows when the function starts and ends - it defines the block


**Exercise 6**: write a function that takes two numbers as input and adds them together, returning the sum of the numbers. Use your function to add the numbers 1 and 3

In [11]:
def add_two_numbers(number1, number2):
    total = number1 + number2
    return total

In [12]:
add_two_numbers(1,3)

4

# Function and Variable names:
Be explicit so that future you knows what you did - in many cases you don't have to keep notes on your code if you use good function and variable names.

# Data types part 3: sequences
* ordered collection
* can refer to whole collection with a single variable

## Lists
* defined with square brakets (e.g. `[`, `]`)
* add to a list: `append` method (in place)
* remove last item: `pop` method (in place)
* conncatonate lists: `+` operator (must set equal to something)
* get a single value from the list: `list[index]`
    - index starts at 0
    - can count backwards, with the index of the last item being -1, second to last -2, etc
* get a subset of a list: slicing `list[start_index: stop_index: step]`
    - brakets must be square
    - includes `start_index` item
    - excludes `end_index` item
    - `step` is optional, default is 1


In [13]:
my_list = [1,2,3, 'a']
my_list.append('b')
print(my_list)

my_list.pop()
print(my_list)

my_list = my_list + ['c', 'd']
print(my_list)

print(my_list[3])

print(my_list[0:3])


[1, 2, 3, 'a', 'b']
[1, 2, 3, 'a']
[1, 2, 3, 'a', 'c', 'd']
a
[1, 2, 3]


**Exercise 7:** Define the variable `odds` to be a list with the odd integers between 1 and 10. Do the following with a list:
* print the first entry
* print the last entry (try using the index that starts counting forward from 0 and the index that counts backwards)
* append the next odd number to your list
* print the second and third entries of the list
* print every other entry
* set the third item in the list to 6
* Bonus: reverse the order of the list


In [14]:
odds = [1,3,5,7,9]
print(odds[0])
print(odds[4], odds[-1])
odds.append(11)
print(odds)
print(odds[1:3])
print(odds[0:5:2])
odds[2] = 6
print(odds)

#Bonus
print(odds[5:0:-1])

1
9 9
[1, 3, 5, 7, 9, 11]
[3, 5]
[1, 5, 9]
[1, 3, 6, 7, 9, 11]
[11, 9, 7, 6, 3]


## Strings

* definition: collection of charaters (letters)
* can access any character just like a list
* Strings are not lists:
    * immutable: cannot be changed
    * no `append` or `pop` method
    * can slice
    * can concatonate


In [15]:
element = 'oxygen'
print(element)
print(element[0])

oxygen
o


**Exercise 8:** 
* try adding an `s` to the end of `element`
* try changing the first letter of `element` to `m` using slicing (i.e. without redefining the whole word).

In [16]:
element = element + 's'
element

'oxygens'

In [17]:
element[0] = 'm'

TypeError: 'str' object does not support item assignment

# Getting Help
* `help` function: works in any python
* `?`: works in the notebook

In [18]:
list.append?

In [19]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

# Loops: Doing something to everything in a collection

What if you wanted to multiply every element of `odd` by 2?

fomula: similar to function   
`for item in list:` <-- item can be any word, colon required  
`    modify item` <-- must be indented

In [20]:
for odd_number in odds:
    print(odd_number *2)

2
6
12
14
18
22


**Exercise 9:** use a loop to print each letter in `element`

In [21]:
for char in element:
    print(char)

o
x
y
g
e
n
s


# Conditional Statements
Do something if a condition is met

formula (like loops and functions):

`if condition:` <-- require colon   
`    thing to do when condition is True`

Conditional operators:
* `==`: equal
* `!=`: not equal
* `>`: greater than
* `<`: less than
* `<=`, `<=`: greater/less than or equal to

Condition: returns `True` or `False` (python data type boolean)

In [22]:
print(element == 'oxygens')
print(element == 'oxygen')

True
False


**Exercise 10**: write a conditional that prints the letter 'O' if the variable element is `'oxygen'`. Test it on your current variable `element` then reassign `element` to be `oxygen` and test the code again

In [23]:
if element == 'oxygen':
    print('O')
    
element = 'oxygen'

if element == 'oxygen':
    print('O')

O


# Packages in Python
* Expand built in (default) toolkit
* collection of files with new definitions (e.g. data types, functions, etc)
* some packages available by default
* some packages you have to install (e.g. like what we did with `sep`)
* make new definitions available to your code: `import package`
* use new definitions: `package.new_function`
    * like a method: tells python where to find the new_function
* For us: package = module = library

# Numpy

* Python package to deal with arrays (like lists but with different rules)
* All elements should be the same data type
    - Fast 
    - Can act on all elements at once
* build with list

In [24]:
import numpy as np

`np` alias (or nickname) so we don't have to type numpy every time. Many packages have conventional aliases that you should use

In [25]:
odds_array = np.array(odds)

**Exercise 11**: How does multiplication act on an array vs a list? Try multiplying `odds` by 2 and `odds_array` by 2. Do you get the same result?

In [26]:
print(odds*2)
print(odds_array*2)

[1, 3, 6, 7, 9, 11, 1, 3, 6, 7, 9, 11]
[ 2  6 12 14 18 22]


## Using `numpy` functions:

In [27]:
np.mean(odds_array)

6.166666666666667

In [28]:
np.std(odds_array)

3.387066905483596

**Exercise 12**: use `np.sum` to add together all of the values in `odds_array`

In [29]:
np.sum(odds_array)

37

# 2D Arrays

We can also have 2D arrays. We will use them a lot when working with astronomical images. Now that we have two dimensions, we must use 2 slices separated by a ``,`` to select elements using the format ``myarray[slice_row,slice_column]``.

**Example:** <font color=blue>Let's define the 3x4 (3 rows, 4 columns) array and do the following operations:</font>
- <font color=blue>View the full array</font>
- <font color=blue>View its shape</font>
- <font color=blue>Print the first entry of the second row</font>
- <font color=blue>Print the entire first row</font>
- <font color=blue>Print the first two elements for each of the last two rows</font>

In [30]:
my_2d_array = np.array([[1, 2, 3, 4],
               [4, 5, 6, 7],
               [8, 9, 10, 11]])
print(my_2d_array)
print(my_2d_array.shape)
print(my_2d_array[1, 0])
print(my_2d_array[1:3, 0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
4
[[4 5]
 [8 9]]


# Dictionaries

Dictionary are very useful in python to store information of any type.
In astronomy a very common use of dictionary is to store all the data connected with one observation with the telescope: exposure time, observer, site of the telescope, temperature of the detector, date of the observation, etc.
Each entry of the dictionary is made up of a *key* paired with a *value*.
To access a value of a dictionary, we use brackets: ``my_dict[key]``.
Each entry is called an `item`. You can access a dictionaries items with `dict.item`, keys with `dict.keys()`, and values with `dict.values`

**Exercise:** <font color=blue>Let's make a simple dictionary and see how we select info from it. Create a dictionary of the element symbols (H, He, Li, Be, B, and C) containing their names (hydrogen, helium, lithium, beryllium, boron, and carbon). Create a loop over the dictionary keys to print each value.</font>

In [31]:
element_dict = {'H': 'hydrogen',
               'He': 'helium',
               'Be': 'beryllium',
               'B': 'boron',
               'C': 'caron'}

for elem_key in element_dict.keys():
    print(element_dict[elem_key])

hydrogen
helium
beryllium
boron
caron


# Reading a text file

Let's use NumPy to read a file.

**Exercise:** <font color=blue>Read an ascii file of the solar spectrum using NumPy.</font>
If you look at the file there are two columns lke this:  
Wavelength (nm)    flux (W*m-2*nm-1)  
xx                 yy  
xx                 yy  
xx                 yy  

In [32]:
data = np.genfromtxt('solar_spectrum_3.txt')
print(data[0:3])

[[2.8000e+02 2.5361e-26]
 [2.8050e+02 1.0917e-24]
 [2.8100e+02 6.1253e-24]]


Now, let's split data in 2 arrays (one for wavelength and one for flux).  
``zip(xx,yy)`` is an aweasome command to combine two arrays.  
``zip(*xxx)`` does the opposite of zip, splits data in 2 arrays.  
(..... I wish someone would have told me about ``zip`` when i started to learn python ....)

In [33]:
wavelength, flux = zip(*data)
print(wavelength)

(280.0, 280.5, 281.0, 281.5, 282.0, 282.5, 283.0, 283.5, 284.0, 284.5, 285.0, 285.5, 286.0, 286.5, 287.0, 287.5, 288.0, 288.5, 289.0, 289.5, 290.0, 290.5, 291.0, 291.5, 292.0, 292.5, 293.0, 293.5, 294.0, 294.5, 295.0, 295.5, 296.0, 296.5, 297.0, 297.5, 298.0, 298.5, 299.0, 299.5, 300.0, 300.5, 301.0, 301.5, 302.0, 302.5, 303.0, 303.5, 304.0, 304.5, 305.0, 305.5, 306.0, 306.5, 307.0, 307.5, 308.0, 308.5, 309.0, 309.5, 310.0, 310.5, 311.0, 311.5, 312.0, 312.5, 313.0, 313.5, 314.0, 314.5, 315.0, 315.5, 316.0, 316.5, 317.0, 317.5, 318.0, 318.5, 319.0, 319.5, 320.0, 320.5, 321.0, 321.5, 322.0, 322.5, 323.0, 323.5, 324.0, 324.5, 325.0, 325.5, 326.0, 326.5, 327.0, 327.5, 328.0, 328.5, 329.0, 329.5, 330.0, 330.5, 331.0, 331.5, 332.0, 332.5, 333.0, 333.5, 334.0, 334.5, 335.0, 335.5, 336.0, 336.5, 337.0, 337.5, 338.0, 338.5, 339.0, 339.5, 340.0, 340.5, 341.0, 341.5, 342.0, 342.5, 343.0, 343.5, 344.0, 344.5, 345.0, 345.5, 346.0, 346.5, 347.0, 347.5, 348.0, 348.5, 349.0, 349.5, 350.0, 350.5, 351.0